data:
  root_dir: C:/Chem_Data/qm9  # Adjusted for QM9 dataset
  target_indices: [0, 3, 5]  
  use_cache: true
  train_split: 0.8
  valid_split: 0.1
  subset_size: 500 #  Specify the subset size

model:
  batch_size: 256
  learning_rate: 0.0070779431649418655
  weight_decay: 1.0908657690794923e-05
  step_size: 50
  gamma: 0.5
  reduce_lr_factor: 0.5
  reduce_lr_patience: 10
  early_stopping_patience: 20
  early_stopping_delta: 0.001
  l1_regularization_lambda: 0.006
  first_layer_type: "transformer_conv" # Adjusted for consistency
  hidden_channels: 512
  second_layer_type: "transformer_conv" # Adjusted for consistency
  dropout_rate: 0.176